version: '3.8'

services:

    evpanel-frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: evpanel-frontend
        restart: always
        ports:
            - 3000:3000
        networks:
            - default

    evpanel-backend:
        build:
            context: backend2
            dockerfile: backend/backend/Dockerfile
        container_name: evpanel-backend2
        restart: always
        ports:
            - 5000:5000
        networks:
            - default