version: '3.8'

services:

    evpanel-frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: evpanel-frontend
        restart: always
        ports:
            - 3000:3000
        networks:
            - evpanel_bridge

    evpanel-backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: evpanel-backend
        restart: always
        ports:
            - 5000:5000
        networks:
            - evpanel_bridge

networks:
    evpanel_bridge:
        external: true
