name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: read-all

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install
      - name: run pytest
        run: |
          pytest --cov=backend --cov-report=xml --cov-report=term-missing

  black:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: get black version
        run: |
          export VERSION=$(grep -Po 'black==\K.*' requirements_dev.txt)
          echo "BLACK_VERSION=$VERSION" >> $GITHUB_ENV
      - name: run black
        uses: psf/black@stable
        with:
          version: ${{ env.BLACK_VERSION }}
          src: "./backend"

