name: Docker Compose Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker Compose configuration
        run: docker-compose up --build -d
      - name: Stop the containers
        run: docker-compose down
